### ISSUE TITLE
Automatically kill background process launched by another background process whenever parent background process is relaunched.

### ISSUE THREAD

**Issue by darkshadow** [litek/gulp-bg#2]
Following is the script that I am using to live reload the gulpfile.js. default task will start a new background process  ```gulp bootstrap``` which in turn starts another background process called ```node app/start.js```. The initial run works as intended. But once I edit gulpfile.js it triggers a watch inside default and kills existing ```gulp bootstrap``` process and starts new ```gulp bootstrap```. But the problem is previous instance of ```node app/start.js``` process is still running. Because  previous instance of node server is not killed and it's still listens on the same port I get an error EADDRINUSE when I ever I edit gulpfile.js.  Is there any way to automatically kill child process ```node app/start.js``` of ```gulp bootstrap``` when ever new ```gulp bootstrap``` process is launched ?

```
var gulp = require('gulp');
var watch = require('gulp-watch');
var bg = require('gulp-bg');

gulp.task('start_server', bg("node", "app/start.js"));

gulp.task('bootstrap', ['start_server'], function() {
    watch("app/**/*", function(){
        gulp.start('start_server');
    });
});

gulp.task('spawn_bootstrap', bg("gulp", "bootstrap"));

gulp.task('default', function(){
    watch('gulpfile.js', function() {
        gulp.start('spawn_bootstrap');
    });
    gulp.start('spawn_bootstrap');
});
```

**Comment by litek** [comment]
It looks like listening to SIGTERM and forcing a shutdown resolves the problem. I'll make an update shortly.

Is there a good reason for spawning multiple gulp processes here, or is it just a simplified example?

**Comment by darkshadow** [comment]
I really liked gulp-bg because I didn't have to write separate task for killing a dev server. I could have done gulp reload spawning using child_process.spawn but I thought why have different ways to do the same thing is not idiomatic. But if gulp-bg implements this feature then gulpfile becomes easy to read.


Thanks for your response and work on gulp-bg.

**Comment by litek** [comment]
Check if this commit fixes your issue, and I'll publish a new version.
